create table
  public.recipe_book (
    id bigint generated by default as identity not null,
    sku text not null,
    name text not null,
    price integer not null default 50,
    demand integer not null default 0,
    red_amt integer not null default 0,
    green_amt integer not null default 0,
    blue_amt integer not null default 0,
    dark_amt integer not null default 0,
    constraint recipe_book_pkey primary key (id),
    constraint recipe_book_name_key unique (name),
    constraint recipe_book_sku_key unique (sku)
  ) tablespace pg_default;

create table
  public.barrel_inventory (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default (now() at time zone 'pst'::text),
    num_red_ml integer not null default 0,
    num_green_ml integer not null default 0,
    num_blue_ml integer not null default 0,
    num_dark_ml integer not null default 0,
    constraint barrel_inventory_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.treasury_log (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default (now() at time zone 'pst'::text),
    gold integer not null default 0,
    constraint treasury_log_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.shop_capacity (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default (now() at time zone 'pst'::text),
    potion_capacity integer not null default 50,
    ml_capacity integer not null default 10000,
    constraint shop_capacity_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.potion_inventory (
    id bigint generated by default as identity not null,
    sku text not null,
    quantity integer not null default 0,
    created_at timestamp with time zone not null default (now() at time zone 'pst'::text),
    constraint potion_inventory_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.carts (
    id bigint generated by default as identity not null,
    customer_name text not null,
    character_class text not null,
    level integer not null,
    time_created timestamp with time zone null,
    constraint carts_pkey primary key (id),
    constraint carts_id_key unique (id)
  ) tablespace pg_default;

create table
  public.carts_items (
    id bigint generated by default as identity not null,
    item_sku text not null,
    quantity integer not null default 0,
    cart_id bigint not null,
    constraint carts_items_pkey primary key (id),
    constraint carts_items_cart_id_fkey foreign key (cart_id) references carts (id) on update cascade on delete cascade,
    constraint carts_items_item_sku_fkey foreign key (item_sku) references potion_inventory (sku) on delete cascade
  ) tablespace pg_default;

create table
  public.time (
    id bigint generated by default as identity not null,
    day text not null,
    hour integer not null,
    constraint time_pkey primary key (id)
  ) tablespace pg_default;
